// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:b70f898f-4483-4d21-9ae2-527e657bb0b8",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Rx2gwa4cP",
    "aws_user_pools_web_client_id": "17cvj3he11mitsae0ihivb7mdi",
    "aws_appsync_graphqlEndpoint": "https://jzogq6s3d5crnd43vidqbrgbhe.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-zvo37lfo4neoncpv5njcvet7iu"
};


export default awsmobile;
